// Generated by Wrangler by running `wrangler types`

interface Env {
	EMAIL_SENDER_USERNAME: "submissions-noreply" | string | {};
	RESEND_CONFIG: string;
	SALT?: string;
	WORKER_ENV?: "local" | string | {};
	CAPTCHA_SECRETS?: string;
  ENCRYPT_EMAIL_PATH?: string;
}
