#:schema node_modules/wrangler/config-schema.json
name = "resend-worker-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-09-19"
compatibility_flags = ["nodejs_compat"]

[vars]
EMAIL_SENDER_USERNAME = "submissions-noreply" # this will translate to: `From: submissions-noreply@yourdomain.com`

[env]
  [env.local]
    [env.local.vars]
      EMAIL_SENDER_USERNAME = "submissions-noreply"
      WORKER_ENV = "local"
