name: Deploy Worker
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      resendConfig:
        description: "Set 'RESEND_CONFIG' (profile: any name, api_key: resend key, domain: domain configured in resend)"
        required: true
        default: "profile=main&api_key=re_abcdef1h_AAb2cd3efg4B5hCiDEFjGklH&domain=yourdomain.com"
      salt:
        description: "Set 'SALT' (any string that will be used to encrypt and decrypt recipients)"
        required: false
        default: "mySuperSecretSaltUsedToEncryptAndDecryptRecipients"
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
        env:
          RESEND_CONFIG: ${{ github.event.inputs.resendConfig }}
          SAILT: ${{ github.event.inputs.salt }}
